### ISSUE TITLE
LDAP Proxy  - Bind SASL GSS-SPNEGO - List index out of range

### ISSUE THREAD

**Issue by sile16** [twisted/ldaptor#157]
A network device is sending the attached bind request to our LDAP proxy that is built on top of [Proxy Base](https://ldaptor.readthedocs.io/en/latest/cookbook/ldap-proxy.html).  We get a list out of range Exception.  

See the attached screenshot from wireshark and the bytes exported into the bin file, also attached.

<img width="696" alt="ldap_bind_gss_wireshark_screenshot" src="https://user-images.githubusercontent.com/536557/70852429-e07ce380-1e66-11ea-9c88-cb228e5bc0ec.png">

This can be reproduced by doing:

nc  10.228.112.141 389 <  ldap_bind_sasl.bin 
[ldap_bind_sasl.bin.zip](https://github.com/twisted/ldaptor/files/3964126/ldap_bind_sasl.bin.zip)

```
2019-12-14 11:36:55-0600 [LoggingProxy,0,172.16.231.167] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
            return self._dataReceived(data)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/root/pureldap/ldapter_proxy/ldaptor/protocols/ldap/ldapserver.py", line 49, in dataReceived
            self.berdecoder, self.buffer)
          File "/root/pureldap/ldapter_proxy/ldaptor/protocols/pureber.py", line 390, in berDecodeObject
            berdecoder=inh)
          File "/root/pureldap/ldapter_proxy/ldaptor/protocols/pureldap.py", line 84, in fromBER
            l = berDecodeMultiple(content, berdecoder)
          File "/root/pureldap/ldapter_proxy/ldaptor/protocols/pureber.py", line 409, in berDecodeMultiple
            n, bytes = berDecodeObject(berdecoder, content)
          File "/root/pureldap/ldapter_proxy/ldaptor/protocols/pureber.py", line 390, in berDecodeObject
            berdecoder=inh)
          File "/root/pureldap/ldapter_proxy/ldaptor/protocols/pureldap.py", line 172, in fromBER
            auth = (l[2][0].value, l[2][1].value)
          File "/usr/lib64/python2.7/UserList.py", line 31, in __getitem__
            def __getitem__(self, i): return self.data[i]
        exceptions.IndexError: list index out of range
```

Environment:

```
# cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
# python --version
Python 2.7.5

ldaptor, had pulled form pip install ldaptor, but now pulled directly from github and seeing the same.  

Package                      Version    
---------------------------- -----------
attrs                        19.3.0     
Automat                      0.8.0      
backports.ssl-match-hostname 3.5.0.1    
cffi                         1.13.2     
chardet                      2.2.1      
configobj                    4.7.2      
configparser                 4.0.2      
constantly                   15.1.0     
cryptography                 2.8        
decorator                    3.4.0      
entrypoints                  0.3        
enum34                       1.1.6      
flake8                       3.7.9      
functools32                  3.2.3.post2
hyperlink                    19.0.0     
idna                         2.8        
incremental                  17.5.0     
iniparse                     0.4        
ipaddress                    1.0.16     
kitchen                      1.1.1      
mccabe                       0.6.1      
passlib                      1.7.2      
perf                         0.1        
pip                          19.3.1     
pyasn1                       0.4.8      
pyasn1-modules               0.2.7      
pycodestyle                  2.5.0      
pycparser                    2.19       
pycurl                       7.19.0     
pyflakes                     2.1.1      
pygobject                    3.22.0     
pygpgme                      0.3        
PyHamcrest                   1.9.0      
pyliblzma                    0.5.3      
pyOpenSSL                    19.1.0     
pyparsing                    2.4.5      
python-linux-procfs          0.4.9      
pyudev                       0.15       
pyxattr                      0.5.1      
schedutils                   0.4        
service-identity             18.1.0     
setuptools                   0.9.8      
six                          1.13.0     
slip                         0.4.0      
slip.dbus                    0.4.0      
Twisted                      19.10.0    
typing                       3.7.4.1    
urlgrabber                   3.10       
yum-metadata-parser          1.1.4      
zope.interface               4.7.1      

```

**Comment by GrayAn** [comment]
Thanks again for your PR :)
