### ISSUE TITLE
Connection lost in proxy server

### ISSUE THREAD

**Issue by fossilet** [twisted/ldaptor#67]
I set up an LDAP proxy using this code http://ldaptor.readthedocs.io/en/latest/cookbook/ldap-proxy.html#code, but I constantly get connection lost errors as in the end. I enabled TCP keepalive for both LoggingProxy.connectionMade and LDAPClient.connectionMade, and I can confirm with `ss` that all the connection from my clients to the proxy and from the proxy to the Active Directory server have keepalive timers. However, the error persists. Hope I can get some hints here. 

```
2016-12-08 15:30:26+0800 [-] Unhandled error in Deferred:
2016-12-08 15:30:26+0800 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallb
acks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/site-packages/ldaptor/protocols/ldap/proxybase.py", line 132, in _
forwardRequestToProxiedServer
            d.addCallback(forwardit, reply)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 319, in addCallback
            callbackKeywords=kw)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 308, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/site-packages/ldaptor/protocols/ldap/proxybase.py", line 129, in forwardit
            self.client.send_noResponse(request)
          File "/usr/lib/python2.7/site-packages/ldaptor/protocols/ldap/ldapclient.py", line 144, in send_noResponse
            msg = self._send(op)
          File "/usr/lib/python2.7/site-packages/ldaptor/protocols/ldap/ldapclient.py", line 77, in _send
            raise LDAPClientConnectionLostException()
        ldaptor.protocols.ldap.ldapclient.LDAPClientConnectionLostException: Connection lost
```

**Comment by psi29a** [comment]
I've only ever used Ldaptor against OpenLDAP and not sure what anyone else has used Ldaptor against. Could there be some changes done by Microsoft in AD that could account for this behavior? Have you tried running OpenLDAP just to test, it would help narrow down the possibilities.

@cwaldbieser ever see this before?

**Comment by cwaldbieser** [comment]
I also use OpenLDAP, though I sometimes test against ldaptor's own LDAP servers.  AD ought to work like any other LDAP server.
I'd suggest in the nested `buildProtocol()` funtion in the example you add `proto.debug = True` prior to returning `proto`.  This will turn debugging on and let you see everything that is going on in your logs.

All I can say for certain from your logs above is that the the proxy (i.e. the ldaptor code) has received a request from a LDAP client that doesn't require a response.  The proxy attempts to send that request to the proxied LDAP server (i.e. AD), but the connection was severed.

Being able to see the AD logs might help you determine why AD dropped the connection.  Something in the debug output from the proxy might also help.

As far as what is supposed to happen in the code-- when your LDAP client connects to the ldaptor service, `connectionMade()` will be fired.  That sets up a callback to `_connectedToProxiedServer()` and an errback to `_failedToConnectToProxiedServer()`, so if something goes wrong at that point, you should see "[ERROR] Could not connect to proxied server." in the log output.

The connection from the proxy to AD is handled by the `ldaptor.protocols.ldapclient.LDAPClient` protocol.  There isn't any logging going on in that protocol, but you could probably subclass it and override `connectionMade()` and `connectionLost()` to log some messages.  Then you could replace `LDAPClient` in the example with your subclass (`MyLoggingLDAPClient`?).

**Comment by fossilet** [comment]
Thanks @cwaldbieser for your help. I will dig with detailed logs and post update.

**Comment by fossilet** [comment]
I've ask the AD administrator, but no interesting logs were provided.

I added logs to the code, and here it is: https://gist.github.com/fossilet/f3f9e492043ba1c6da15368fc0ad98d6.

I am using Jira as the client. The problem is that LDAPClient tries to send command via a lost connection, though the connection (0x7f813b3b0310) from the proxy (10.20.20.82) to the AD server (10.20.95.51) is already lost.

```
2016-12-12 15:32:23+0800 [Uninitialized] P -> S CONN MADE: 0x7f813b3b0310 10.20.20.82:54909 <-> 10.20.95.51:389.
...
...
2016-12-12 15:47:57+0800 [MyLDAPClient,client] P -> S CONN LOST: 0x7f813b3b0310 <<class 'twisted.internet.tcp.Client'> to ('dc.corp.ncfgroup.com', 389) at 7f813b3b0310>
2016-12-12 15:47:57+0800 [-] Stopping factory <twisted.internet.endpoints.OneShotFactory instance at 0x7f813b3ae3f8>
2016-12-12 15:54:50+0800 [LoggingProxy,3,10.20.95.84] UNEXPECTED P -> S CONN LOST: 0x7f813b3b0310 <<class 'twisted.internet.tcp.Client'> to ('dc.corp.ncfgroup.com', 389) at 7f813b3b0310>
2016-12-12 15:54:50+0800 [-] Unhandled error in Deferred:
2016-12-12 15:54:50+0800 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/site-packages/ldaptor/protocols/ldap/proxybase.py", line 132, in _forwardRequestToProxiedServer
            d.addCallback(forwardit, reply)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 319, in addCallback
            callbackKeywords=kw)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 308, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/site-packages/ldaptor/protocols/ldap/proxybase.py", line 126, in forwardit
            dseq)
          File "/usr/lib/python2.7/site-packages/ldaptor/protocols/ldap/ldapclient.py", line 129, in send_multiResponse
            msg = self._send(op)
          File "/root/sso/scripts/proxy.py", line 119, in _send
            raise LDAPClientConnectionLostException()
        ldaptor.protocols.ldap.ldapclient.LDAPClientConnectionLostException: Connection lost

**Comment by fossilet** [comment]
I've ask the AD administrator, but no interesting logs were provided.

I added logs to the code, and here it is: https://gist.github.com/fossilet/f3f9e492043ba1c6da15368fc0ad98d6.

I am using Jira as the client. The problem is that LDAPClient tries to send command via a lost connection, though the connection (0x7f813b3b0310) from the proxy (10.20.20.82) to the AD server (10.20.95.51) is already lost.

```
2016-12-12 15:32:23+0800 [Uninitialized] P -> S CONN MADE: 0x7f813b3b0310 10.20.20.82:54909 <-> 10.20.95.51:389.
...
...
2016-12-12 15:47:57+0800 [MyLDAPClient,client] P -> S CONN LOST: 0x7f813b3b0310 <<class 'twisted.internet.tcp.Client'> to ('ad.server', 389) at 7f813b3b0310>
2016-12-12 15:47:57+0800 [-] Stopping factory <twisted.internet.endpoints.OneShotFactory instance at 0x7f813b3ae3f8>
2016-12-12 15:54:50+0800 [LoggingProxy,3,10.20.95.84] UNEXPECTED P -> S CONN LOST: 0x7f813b3b0310 <<class 'twisted.internet.tcp.Client'> to ('ad.server', 389) at 7f813b3b0310>
2016-12-12 15:54:50+0800 [-] Unhandled error in Deferred:
2016-12-12 15:54:50+0800 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/site-packages/ldaptor/protocols/ldap/proxybase.py", line 132, in _forwardRequestToProxiedServer
            d.addCallback(forwardit, reply)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 319, in addCallback
            callbackKeywords=kw)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 308, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/site-packages/ldaptor/protocols/ldap/proxybase.py", line 126, in forwardit
            dseq)
          File "/usr/lib/python2.7/site-packages/ldaptor/protocols/ldap/ldapclient.py", line 129, in send_multiResponse
            msg = self._send(op)
          File "/root/sso/scripts/proxy.py", line 119, in _send
            raise LDAPClientConnectionLostException()
        ldaptor.protocols.ldap.ldapclient.LDAPClientConnectionLostException: Connection lost

**Comment by cwaldbieser** [comment]
If you log the `reason` parameter in the `connectionLost()` method of your
proxy client, what is the error code?

**Comment by fossilet** [comment]
I caught the reason as below, but there seems to be no error code.

Besides the connection in problem, the OneShotFactory associated with the connection also gets lost after a long period of time. Should it be teared as soon as possible? I also find the connection is lost in this fashion every N*15 minutes; I have logs for 15, 30, and 45 minutes.

With `ldapsearch` command, the OneShotFactory and the proxy-to-server connection is severed as longs as the command exits, so there is no such problem.

> 2016-12-13 11:19:47+0800 [-] Starting factory <twisted.internet.endpoints.OneShotFactory instance at 0x7f1268372fc8>
2016-12-13 11:19:47+0800 [twisted.internet.protocol.ServerFactory] C -> P CONN MADE: 0x7f1268388890 10.20.95.84:36094 <-> 10.20.20.82:389
2016-12-13 11:19:51+0800 [Uninitialized] P -> S CONN MADE: 0x7f1268388910 10.20.20.82:45487 <-> 10.20.95.12:389.
> ......
> 2016-12-13 11:54:11+0800 [MyLDAPClient,client] P -> S CONN LOST: 0x7f1268388910 <<class 'twisted.internet.tcp.Client'> to ('dc.corp.ncfgroup.com', 389) at 7f1268388910>. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.

**Comment by fossilet** [comment]
I caught the reason as below, but there seems to be no error code.

Besides the connection in problem, the OneShotFactory associated with the connection also gets lost after a long period of time. Should it be teared as soon as possible? I also find the connection is lost in this fashion every N*15 minutes; I have logs for 15, 30, and 45 minutes.

With `ldapsearch` command, the OneShotFactory and the proxy-to-server connection is severed as longs as the command exits, so there is no such problem.

> 2016-12-13 11:19:47+0800 [-] Starting factory <twisted.internet.endpoints.OneShotFactory instance at 0x7f1268372fc8>
2016-12-13 11:19:47+0800 [twisted.internet.protocol.ServerFactory] C -> P CONN MADE: 0x7f1268388890 10.20.95.84:36094 <-> 10.20.20.82:389
2016-12-13 11:19:51+0800 [Uninitialized] P -> S CONN MADE: 0x7f1268388910 10.20.20.82:45487 <-> 10.20.95.12:389.
> ......
> 2016-12-13 11:54:11+0800 [MyLDAPClient,client] P -> S CONN LOST: 0x7f1268388910 <<class 'twisted.internet.tcp.Client'> to ('ad.server', 389) at 7f1268388910>. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.

**Comment by cwaldbieser** [comment]
I'm not sure about the timing of the `OneShotFactory`.  I'd expect it to be torn down fairly soon after the connection closed.
It sounds like the connection is being either shut down by AD or something in between like a firewall.
Even though each LDAP connection typically has multiple requests and responses, the connections tend to be pretty short lived in most cases.  E.g. Client connects, negotiates startTLS, BINDs as some DN, does a SEARCH or 2, maybe a MOD, then UNBINDs.

Maybe if you could show what options you are using for the `ldapsearch` command, it would give us some idea how the actual client is connecting and what might be going wrong.

**Comment by cwaldbieser** [comment]
To follow up on the `OneShotFactory`-- I ran the LDAP server from the quick start.  I then ran the `ldaptor.protocols.ldap.proxbase` module directly.  Finally, I made a query against the proxy.  Here are the log results:

    2016-12-13 18:31:36-0500 [-] Starting factory <twisted.internet.endpoints.OneShotFactory instance at 0x7f691949ef80>
    2016-12-13 18:31:36-0500 [LDAPClient,client] Received response from proxied service: LDAPSearchResultEntry(objectName='dc=org', attributes=[('objectClass', ['dcObject']), ('dc', ['org'])]
    2016-12-13 18:31:36-0500 [LDAPClient,client] Received response from proxied service: LDAPSearchResultEntry(objectName='dc=example,dc=org', attributes=[('objectClass', ['dcObject', 'organization']), ('dc', ['example'])]
    2016-12-13 18:31:36-0500 [LDAPClient,client] Received response from proxied service: LDAPSearchResultEntry(objectName='ou=people,dc=example,dc=org', attributes=[('objectClass', ['organizationalUnit']), ('ou', ['people'])]
    2016-12-13 18:31:36-0500 [LDAPClient,client] Received response from proxied service: LDAPSearchResultEntry(objectName='gn=John+sn=Smith,ou=people,dc=example,dc=org', attributes=[('objectClass', ['addressbookPerson']), ('description', ['This is a description that can span multiple lines as long as the non-first lines are indented in the LDIF.']), ('facsimileTelephoneNumber', ['555-1235']), ('gn', ['John']), ('sn', ['Smith']), ('telephoneNumber', ['555-1234']), ('userPassword', ['eekretsay'])]
    2016-12-13 18:31:36-0500 [LDAPClient,client] Received response from proxied service: LDAPSearchResultEntry(objectName='gn=John+sn=Doe,ou=people,dc=example,dc=org', attributes=[('objectClass', ['addressbookPerson']), ('c', ['US']), ('gn', ['John']), ('l', ['New York City']), ('postOfficeBox', ['123']), ('postalAddress', ['Backstreet']), ('postalCode', ['54321']), ('sn', ['Doe']), ('st', ['NY']), ('street', ['Back alley']), ('userPassword', ['terces'])]
    2016-12-13 18:31:36-0500 [LDAPClient,client] Received response from proxied service: LDAPSearchResultEntry(objectName='cn=bob,ou=people,dc=example,dc=org', attributes=[('objectClass', ['inetOrgPerson', 'person', 'top']), ('cn', ['bob']), ('gn', ['Bob']), ('mail', ['bob@example.org']), ('sn', ['Roberts']), ('userPassword', ['secret'])]
    2016-12-13 18:31:36-0500 [LDAPClient,client] Received response from proxied service: LDAPSearchResultDone(resultCode=0L)
    2016-12-13 18:31:36-0500 [-] Stopping factory <twisted.internet.endpoints.OneShotFactory instance at 0x7f691949ef80>

As you can see, the `OneShotFactory` instance is created when the client connects to the proxy.  After the client issues an UNBIND request which disconnects it from the proxy, the `OneShotFactory` instance is torn down pretty quickly.

[1] http://ldaptor.readthedocs.io/en/latest/quickstart.html#ldap-server-quick-start

**Comment by fossilet** [comment]
I possibly have figured out the problem. Confluence maintains a connection pool to the proxy, so the connections between the client and the proxy and between the proxy and the server are both alive after a first search request. However, the connection between the proxy and server get severed after a certain amount of time, but the client is not aware of it. When subsequent requests from the client try to reuse the connections, the client finds that the other part, the connection from the proxy and server, is lost.

Is there a way to cut the client-to-proxy connection when a proxy-to-server connection is lost? And possibly vice versa? I think this would make the connection clean.

**Comment by psi29a** [comment]
Is this an issue of connection lost propagation?

**Comment by cwaldbieser** [comment]
If I understand correctly, the issue is that the client (Jira) maintains a long lasting LDAP connection.  The proxy makes a long lasting connection to the server, but the server (AD) doesn't want to maintain long connections, so after some time it drops the proxy-to-server connection.  The client (Jira) is unaware.

The thing to do would be when you create a `clientConnector` on your LDAP proxy protocol (derived from `ProxyBase`), you would need to create instances of `LDAPClient` that had their `connectionLost()` methods hooked up to something.  You'd probably want it to call `queue()` on your `ProxyBase` protocol and have it send an unsolicited response [1] to the client to warn it that the connection was about to drop, and ten break the connection with `self.transport.close()`.

It sounds a lot more complicated than it is.  Simply put, when the proxy-to-server connection closes unexpectedly, the proxy should notify the client and close its connection.

[1] https://tools.ietf.org/html/rfc4511#section-4.4

**Comment by fossilet** [comment]
@cwaldbieser I did exactly what you advised, and solved the problem. Many thanks to your detailed help, otherwise I'd still be stuck here.

**Comment by psi29a** [comment]
@fossilet Great to hear that you figured it out.

@cwaldbieser Thank you for taking the time to answer! :)

**Comment by Well-am** [comment]
@fossilet Hello, I know that years passed from your last message in this thread, but maybe you can find how you fixed that problem and publish code? I have exactly the same problem in old script at our server, and can't fix it myself

**Comment by fossilet** [comment]
@Well-am it really was a long time. I have made the repo public, and you can look at `connectionLost` method at https://github.com/fossilet/sso/blob/master/proxy.py#L128. Hope it helps.
