### ISSUE TITLE
None is neither bytes nor unicode

### ISSUE THREAD

**Issue by alvaro-gh** [twisted/ldaptor#97]
I'm trying to set up the merger example and I don't know why default bindAddress=None is not working at https://github.com/twisted/ldaptor/blob/4e2b67798b75e0c2b364fc0d9fdf327b0f0ddca4/ldaptor/protocols/ldap/ldapconnector.py#L29

My code is (Python 2.7.14):
```
from twisted.internet import defer, reactor, protocol
from twisted.python import log
from ldaptor.config import LDAPConfig
from ldaptor.protocols.ldap.merger import MergedLDAPServer
from six.moves.queue import Queue
import sys

log.startLogging(sys.stderr)

configs = [LDAPConfig(serviceLocationOverrides={'dc=example,dc=com': ('some_host', 389)}),
           LDAPConfig(serviceLocationOverrides={'dc=example.dc=org': ('other_host', 636)})]
use_tls = [False,True]
factory = protocol.ServerFactory()
factory.protocol = lambda: MergedLDAPServer(configs, use_tls)
reactor.listenTCP(8389, factory)
    
reactor.run()
```
And trace:
```
2018-01-18 21:36:59+0000 [-] Log opened.
2018-01-18 21:36:59+0000 [-] ServerFactory starting on 8389
2018-01-18 21:36:59+0000 [-] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x7f991a0e7320>
2018-01-18 21:37:03+0000 [twisted.internet.protocol.ServerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1073, in doRead
	    protocol.makeConnection(transport)
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py", line 510, in makeConnection
	    self.connectionMade()
	  File "/usr/local/lib/python2.7/site-packages/ldaptor/protocols/ldap/merger.py", line 88, in connectionMade
	    overrides=c.getServiceLocationOverrides())
	  File "/usr/local/lib/python2.7/site-packages/ldaptor/protocols/ldap/ldapconnector.py", line 113, in connect
	    bindAddress=bindAddress)
	  File "/usr/local/lib/python2.7/site-packages/ldaptor/protocols/ldap/ldapconnector.py", line 39, in __init__
	    connectFuncKwArgs={'bindAddress': bindAddress})
	  File "/usr/local/lib/python2.7/site-packages/twisted/names/srvconnect.py", line 77, in __init__
	    self.domain = nativeString(domain)
	  File "/usr/local/lib/python2.7/site-packages/twisted/python/compat.py", line 412, in nativeString
	    raise TypeError("%r is neither bytes nor unicode" % s)
	exceptions.TypeError: None is neither bytes nor unicode
```

**Comment by psi29a** [comment]
What version of Twisted are you running?

**Comment by mxdlx** [comment]
Hi @psi29a, thanks for replying.
```
root@7cfc500925db:~# pip list | grep Twisted
Twisted (17.9.0) 
```

**Comment by jojo2024** [comment]
Hi,
I fall on the same problem when I tried to run a code which worked on Ubuntu Xenial 16.04 (twisted 16.0.0) on Ubuntu Bionic 18.04 (twisted 17.9.0).
Thanks to this report, I have a workaround.
Could Ldaptor maintainers ask Ubuntu for upgrading the packaged version ? Ldaptor 
0.0.43 is provided for many years now : https://launchpad.net/ldaptor/+packages ;)
Thanks.

**Comment by psi29a** [comment]
Fixed on master — ldaptor/protocols/ldap/ldapconnector.py:23 does domain = dn.getDomainName() or ""
