### ISSUE TITLE
Unknown command test-ldapserver.tac when running readme

### ISSUE THREAD

**Issue by jaraco** [twisted/ldaptor#98]
I tried to run the ldap server according to the docs in the readme, but got an "Unknown command" error response:

```
$ python -m venv ~/.envs/ldaptor
$ ~/.envs/ldaptor/bin/pip install ldaptor
Collecting ldaptor
  Using cached ldaptor-16.0.1-py2.py3-none-any.whl
Collecting PyCrypto (from ldaptor)
Collecting Twisted (from ldaptor)
Collecting pyOpenSSL (from ldaptor)
  Using cached pyOpenSSL-17.5.0-py2.py3-none-any.whl
Collecting pyparsing (from ldaptor)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting zope.interface (from ldaptor)
Collecting hyperlink>=17.1.1 (from Twisted->ldaptor)
  Using cached hyperlink-18.0.0-py2.py3-none-any.whl
Collecting constantly>=15.1 (from Twisted->ldaptor)
  Using cached constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from Twisted->ldaptor)
  Using cached incremental-17.5.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from Twisted->ldaptor)
  Using cached Automat-0.6.0-py2.py3-none-any.whl
Collecting cryptography>=2.1.4 (from pyOpenSSL->ldaptor)
  Using cached cryptography-2.2.2-cp34-abi3-macosx_10_6_intel.whl
Collecting six>=1.5.2 (from pyOpenSSL->ldaptor)
  Using cached six-1.11.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.envs/ldaptor/lib/python3.7/site-packages (from zope.interface->ldaptor)
Collecting idna>=2.5 (from hyperlink>=17.1.1->Twisted->ldaptor)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting attrs (from Automat>=0.3.0->Twisted->ldaptor)
  Using cached attrs-17.4.0-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=2.1.4->pyOpenSSL->ldaptor)
  Using cached asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=2.1.4->pyOpenSSL->ldaptor)
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyOpenSSL->ldaptor)
Installing collected packages: PyCrypto, idna, hyperlink, constantly, incremental, six, attrs, Automat, zope.interface, Twisted, asn1crypto, pycparser, cffi, cryptography, pyOpenSSL, pyparsing, ldaptor
Successfully installed Automat-0.6.0 PyCrypto-2.6.1 Twisted-17.9.0 asn1crypto-0.24.0 attrs-17.4.0 cffi-1.11.5 constantly-15.1.0 cryptography-2.2.2 hyperlink-18.0.0 idna-2.6 incremental-17.5.0 ldaptor-16.0.1 pyOpenSSL-17.5.0 pycparser-2.18 pyparsing-2.2.0 six-1.11.0 zope.interface-4.4.3
$ ~/.envs/ldaptor/bin/twistd -ny --pidfile=ldapserver.pid --logfile=ldapserver.log test-ldapserver.tac
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Usage: twistd [options]
Options:
  -b, --debug          Run the application in the Python Debugger (implies
                       nodaemon),         sending SIGUSR2 will drop into
                       debugger
      --chroot=        Chroot to a supplied directory before running
  -d, --rundir=        Change to a supplied directory before running [default:
                       .]
  -e, --encrypted      The specified tap/aos file is encrypted.
      --euid           Set only effective user-id rather than real user-id.
                       (This option has no effect unless the server is running
                       as root, in which case it means not to shed all
                       privileges after binding ports, retaining the option to
                       regain privileges in cases such as spawning processes.
                       Use with caution.)
  -f, --file=          read the given .tap file [default: twistd.tap]
  -g, --gid=           The gid to run as.
      --help           Display this help and exit.
      --help-reactors  Display a list of possibly available reactor names.
  -l, --logfile=       log to a specified file, - for stdout
      --logger=        A fully-qualified name to a log observer factory to use
                       for the initial log observer.  Takes precedence over
                       --logfile and --syslog (when available).
  -n, --nodaemon       don't daemonize, don't use default umask of 0077
  -o, --no_save        do not save state on shutdown
      --originalname   Don't try to change the process name
  -p, --profile=       Run in profile mode, dumping results to specified file.
      --pidfile=       Name of the pidfile [default: twistd.pid]
      --prefix=        use the given prefix when syslogging [default: twisted]
      --profiler=      Name of the profiler to use (profile, cprofile).
                       [default: cprofile]
  -r, --reactor=       Which reactor to use (see --help-reactors for a list of
                       possibilities)
  -s, --source=        Read an application from a .tas file (AOT format).
      --savestats      save the Stats object rather than the text output of the
                       profiler.
      --spew           Print an insanely verbose log of everything that happens.
                       Useful when debugging freezes or locks in complex code.
      --syslog         Log to syslog, not to file
  -u, --uid=           The uid to run as.
      --umask=         The (octal) file creation mask to apply.
      --version        Print version information and exit.
  -y, --python=        read an application from within a Python file (implies
                       -o)

twistd reads a twisted.application.service.Application out of a file and runs
it.
Commands:
    conch            A Conch SSH service.
    dns              A domain name server.
    ftp              An FTP server.
    inetd            An inetd(8) replacement.
    manhole          An interactive remote debugger service accessible via
                     telnet and ssh and providing syntax coloring and basic line
                     editing functionality.
    portforward      A simple port-forwarder.
    procmon          A process watchdog / supervisor
    socks            A SOCKSv4 proxy service.
    web              A general-purpose web server which can serve from a
                     filesystem or application resource.
    words            A modern words server
    xmpp-router      An XMPP Router server

/Users/jaraco/.envs/ldaptor/bin/twistd: Unknown command: test-ldapserver.tac
```

**Comment by jaraco** [comment]
That was a pip install on Python 3.7b3.

By re-arranging the parameters, to put `-y` directly in front of the test-ldapserver.tac, I get a different error, an error which is likely due to this library not yet supporting Python 3.

I tried to replicate this error on Python 2, but have not yet had any luck building PyCrypto for Python 2.

**Comment by jaraco** [comment]
After forcing install of pycrypto==2.3, I was able to install ldaptor, and was able to confirm that passing `-y` must be followed immediately by the python file name. 

Correcting that usage, I got another error, suggesting that the test server must be run in the context of the ldaptor repo.

```
$ ~/.virtualenvs/ldaptor/bin/twistd -n --pidfile=ldapserver.pid --logfile=ldapserver.log -y test-ldapserver.tac
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Unhandled Error
Traceback (most recent call last):
  File "/Users/jaraco/.virtualenvs/ldaptor/lib/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/Users/jaraco/.virtualenvs/ldaptor/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/Users/jaraco/.virtualenvs/ldaptor/lib/python2.7/site-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/Users/jaraco/.virtualenvs/ldaptor/lib/python2.7/site-packages/twisted/application/app.py", line 445, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/Users/jaraco/.virtualenvs/ldaptor/lib/python2.7/site-packages/twisted/application/app.py", line 456, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/Users/jaraco/.virtualenvs/ldaptor/lib/python2.7/site-packages/twisted/application/service.py", line 412, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/Users/jaraco/.virtualenvs/ldaptor/lib/python2.7/site-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "test-ldapserver.tac", line 13, in <module>
    shutil.copytree(DBPATH, TMPDBPATH)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 185, in copytree
    names = os.listdir(src)
exceptions.OSError: [Errno 2] No such file or directory: 'ldaptor/test/ldif/webtests'


Failed to load application: [Errno 2] No such file or directory: 'ldaptor/test/ldif/webtests'
```

So in addition to correcting the usage, I suggest the docs should either recommend checkout out the repo or creating that file. The former is better because it also incorporates downloading the .tac file, which is currently an implied operation.
